import type { FreeProxyItem, FreeProxySyncResult, FreeProxyProvider } from "./types";
import { isPrivateHost } from "@/shared/network/outboundUrlGuard";
import { readFile } from "fs/promises";
import { existsSync } from "fs";

const DEFAULT_PROXIES_FILE = "./proxies/http.txt";
const DEFAULT_MAX = 1000;

/**
 * ProxyScraperProvider integrates with monosans/proxy-scraper-checker
 * Reads validated proxies from text files generated by the scraper
 */
export class ProxyScraperProvider implements FreeProxyProvider {
  readonly id = "proxyscraper" as const;
  readonly name = "ProxyScraper";

  isEnabled(): boolean {
    return process.env.FREE_PROXY_SCRAPER_ENABLED === "true";
  }

  private getConfig() {
    return {
      httpFile: process.env.FREE_PROXY_SCRAPER_HTTP_FILE || DEFAULT_PROXIES_FILE,
      socks4File: process.env.FREE_PROXY_SCRAPER_SOCKS4_FILE || "./proxies/socks4.txt",
      socks5File: process.env.FREE_PROXY_SCRAPER_SOCKS5_FILE || "./proxies/socks5.txt",
      maxProxies: parseInt(process.env.FREE_PROXY_SCRAPER_MAX || "", 10) || DEFAULT_MAX,
    };
  }

  async sync(): Promise<FreeProxySyncResult> {
    if (!this.isEnabled()) {
      return { fetched: 0, added: 0, updated: 0, errors: ["ProxyScraper provider disabled"] };
    }

    const { upsertFreeProxy } = await import("../db/freeProxies");
    const config = this.getConfig();
    const errors: string[] = [];
    let added = 0;
    let updated = 0;
    let fetched = 0;

    // Process each proxy type file
    const files = [
      { path: config.httpFile, type: "http" as const },
      { path: config.socks4File, type: "socks4" as const },
      { path: config.socks5File, type: "socks5" as const },
    ];

    for (const { path, type } of files) {
      try {
        if (!existsSync(path)) {
          errors.push(`File not found: ${path}`);
          continue;
        }

        const content = await readFile(path, "utf-8");
        const lines = content.split("\n").filter((line) => line.trim());

        const proxies = lines.slice(0, config.maxProxies);
        fetched += proxies.length;

        for (const line of proxies) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith("#")) continue;

          const [host, portStr] = trimmed.split(":");
          const port = parseInt(portStr, 10);

          if (!host || !port || isNaN(port) || isPrivateHost(host)) {
            errors.push(`proxyscraper: skipped invalid/private host ${host}`);
            continue;
          }

          const item: FreeProxyItem = {
            source: "proxyscraper",
            host,
            port,
            type,
            countryCode: null,
            qualityScore: 60, // proxy-scraper-checker validates these
            latencyMs: null,
            anonymity: "anonymous",
            lastValidated: new Date().toISOString(),
          };

          const result = await upsertFreeProxy(item);
          if (result.action === "created") added++;
          else updated++;
        }
      } catch (err) {
        errors.push(`${type}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    return { fetched, added, updated, errors };
  }

  async list(filters: {
    protocol?: string;
    country?: string;
    minQuality?: number;
    limit?: number;
  }): Promise<FreeProxyItem[]> {
    const { listFreeProxiesBySource } = await import("../db/freeProxies");
    return listFreeProxiesBySource("proxyscraper", filters);
  }
}
